lucee/lucee-data-provider

download/functions.cfm
Updating message about Lucee 5 so it says it is ready for production use.
=> Updating message about Lucee 5

download/index.cfm, download/index1.cfm
`<style>` has been updated to tidy things up on download pages.
todo: update html markup to make it semantic and valid.
=> update `<style>` for download pages

download/index.cfm
=> varscoping LDEV-2666

extension/ExtensionProvider.cfc
projectUrl,sourceUrl,documentionUrl
https://luceeserver.atlassian.net/browse/LDEV-1703
=> add support for additional metadata urls LDEV-1703

download/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-3887
https://luceeserver.atlassian.net/browse/LDEV-3284
=> Corrected the extension version order and updated some recent changes

update/S3.cfc
prevent overlapping builds
https://luceeserver.atlassian.net/browse/LDEV-4273
=> LDEV-4273 add a lock around building artifacts

update/MavenMatcher.cfc
https://luceeserver.atlassian.net/browse/LDEV-4299
=> LDEV-4299 add mwiede jsch to maven matcher

update/UpdateProvider.cfc
https://luceeserver.atlassian.net/browse/LDEV-4322
=> allow configuring statuscode, mimetype and charset for echoGet

.github/workflows/main.yml, .gitignore, extension/S3Ext.cfc, tests/Syntax.cfc
https://luceeserver.atlassian.net/browse/LDEV-4346
=> LDEV-4346 optimize extension update provider

update/build/website/index.cfm
Update links in the sample home page to point to the latest/appropriate URLs for Git repo, JIRA, Dev forums, etc
=> update sample home page links

download/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-4420
=> Added a fix to remove duplicate data on the lucee download changelog page for LDEV-4420

apps/updateserver/Application.cfc, apps/updateserver/rest/UpdateProvider.cfc, apps/updateserver/services/JiraChangeLogService.cfc, apps/updateserver/services/VersionUtils.cfc, apps/updateserver/services/legacy/Jira.cfc, apps/updateserver/services/legacy/MavenRepo.cfc, apps/updateserver/services/legacy/S3.cfc
- cache issues as json to s3
- cache changelogs 
- check for updates on load (every 15 mins)
- async refresh
- refactor toVersionSortable to VersionUtils as static function, with 1 day cache
=> jira change log service

apps/updateserver/services/legacy/S3.cfc, tests/testBuildArtifacts.cfc
- add a test for artifact production (light, zero, war, fb, express etc)
- fix build paths
- use unique temp directories for each artifact build
=> Artifact integration tests and fix build paths

apps/updateserver/services/legacy/S3.cfc, apps/updateserver/services/legacy/build/war-6.2/WEB-INF/web.xml, tests/testBuildArtifacts.cfc
https://luceeserver.atlassian.net/browse/LDEV-5047
=> LDEV-5047 lucee 6.2 war support

apps/download/Application.cfc, apps/download/_header.cfm, apps/download/_linkbar.cfm, apps/download/changelog/index.cfm, apps/download/download.cfc, apps/download/index.cfm, apps/download/res/site.css, apps/updateserver/Application.cfc, apps/updateserver/ApplicationProxy.cfc, apps/updateserver/rest/Application.cfc, apps/updateserver/rest/UpdateProvider.cfc, apps/updateserver/services/JiraChangeLogService.cfc, apps/updateserver/services/legacy/Jira.cfc, apps/updateserver/services/legacy/MavenRepo.cfc, devops/.CFconfig-download.json5, devops/.CFconfig-sentry.json, devops/.CFconfig-update.json5, devops/Dockerfile.base, devops/Dockerfile.download, devops/Dockerfile.update
https://luceeserver.atlassian.net/browse/LDEV-2535
- major refactor
- update to 6.2.0.231
- add changelogs page
- add toolbar links
=> LDEV-2535 add /changelog

apps/download/Application.cfc, apps/updateserver/Application.cfc, apps/updateserver/services/BundleDownloadService.cfc, apps/updateserver/services/ExtensionMetadataReader.cfc, apps/updateserver/services/legacy/MavenRepo.cfc, apps/updateserver/services/legacy/S3.cfc, apps/updateserver/services/legacy/expressTemplates.cfc, devops/.CFconfig-sentry.json, tests/testBuildArtifacts.cfc
https://luceeserver.atlassian.net/browse/LDEV-5367
=> LDEV-5367 use express templates for builds

apps/download/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-5402
=> Added the fix for LDEV-5402.

apps/download/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-5402
=> Updated the index.cfm for LDEV-5402.

apps/updateserver/services/legacy/MavenRepo.cfc, apps/updateserver/services/legacy/S3.cfc, tests/testBuildArtifacts.cfc
https://luceeserver.atlassian.net/browse/LDEV-5451
=> LDEV-5451 Lucee 7 / Commandbox 6.20 / Jakarta support

apps/download/changelog/index.cfm, apps/download/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-5445
=> LDEV-5445 showcase 7 snapshots on download page

apps/updateserver/services/legacy/S3.cfc, apps/updateserver/services/legacy/build/war-7.0/WEB-INF/web.xml
https://luceeserver.atlassian.net/browse/LDEV-5451
=> LDEV-5451 add support for jakarta only wars

apps/download/changelog/index.cfm
https://luceeserver.atlassian.net/browse/LDEV-5470
=> LDEV-5470 show pending snapshots before a release on the change log

apps/download/Application.cfc, apps/download/extensionMeta.json, apps/download/index.cfm, tests/testExtensions.cfc
https://luceeserver.atlassian.net/browse/LDEV-5497
=> LDEV-5497 add links to extensions on download page (src, docs, repo)

apps/ai/www/v1/components/org/lucee/ai/rag/RAG.cfc, apps/download/download.cfc, apps/download/index.cfm, apps/updateserver/services/ExtensionMetadataReader.cfc
https://luceeserver.atlassian.net/browse/LDEV-5490
=> LDEV-5490 show extension min core version on downloads page
